#存储所有全局配置和常量，方便统一管理和修改。

# --- Layout Settings ---
SCREEN_WIDTH, SCREEN_HEIGHT = 1050, 800
MAZE_AREA_SIZE = 780
MAZE_AREA_X = (SCREEN_HEIGHT - MAZE_AREA_SIZE) // 2
MAZE_AREA_Y = (SCREEN_HEIGHT - MAZE_AREA_SIZE) // 2
INFO_PANEL_WIDTH = SCREEN_WIDTH - MAZE_AREA_SIZE - MAZE_AREA_X
INFO_PANEL_X = MAZE_AREA_X + MAZE_AREA_SIZE
FPS = 60

# --- Color Palette ---
COLOR_BG = (135, 206, 235)
COLOR_WALL = (146, 209, 79)
COLOR_PATH = (245, 245, 245)
COLOR_GRID = (189, 215, 166)
COLOR_HUD_BG = (44, 62, 80)
COLOR_TEXT = (255, 255, 255)
COLOR_SUBTEXT = (255, 236, 139)
COLOR_BTN = (221, 46, 68)
COLOR_BTN_HOVER = (252, 212, 0)
COLOR_BTN_SHADOW = (161, 26, 48)
COLOR_DP_PATH = (255, 69, 0, 150)

# --- Game States ---
STATE_MAIN_MENU = 'main_menu'
STATE_INSTRUCTIONS = 'instructions'
STATE_SELECT_MODE = 'select_mode'
STATE_GAMEPLAY = 'gameplay'
STATE_QUIT = 'quit'

# --- Maze Element Constants ---
WALL, PATH, START, END, BOSS, LOCKER, GOLD, TRAP, HEALTH_POTION, SHOP = range(10)

# --- Algorithm Types ---
ALGO_GREEDY = 'Greedy (Real-time)'
ALGO_DP_VISUALIZATION = 'DP (Optimal Path)'
ALGO_RANDOM = 'Random Walk (Baseline)'

# --- Maze Element Color Mapping ---
TILE_TYPE_COLORS = {
    WALL: COLOR_WALL, PATH: COLOR_PATH, START: (19, 201, 242), END: (221, 46, 68),
    BOSS: COLOR_PATH, LOCKER: COLOR_PATH, GOLD: COLOR_PATH, TRAP: COLOR_PATH,
    HEALTH_POTION: COLOR_PATH, SHOP: COLOR_PATH,
}

# --- 【功能新增】游戏机制量化 ---
TRAP_GOLD_COST = 15
TRAP_HEALTH_COST = 20
GOLD_REWARD = 10
POTION_HEAL_AMOUNT = 20
